<?php
/**
 * GetCharactersCharacterIdStats200OkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetCharactersCharacterIdStats200OkTest Class Doc Comment
 *
 * @category    Class */
// * @description Aggregate stats for a year
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetCharactersCharacterIdStats200OkTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetCharactersCharacterIdStats200Ok"
     */
    public function testGetCharactersCharacterIdStats200Ok()
    {
    }

    /**
     * Test attribute "year"
     */
    public function testPropertyYear()
    {
    }

    /**
     * Test attribute "character_minutes"
     */
    public function testPropertyCharacterMinutes()
    {
    }

    /**
     * Test attribute "character_sessions_started"
     */
    public function testPropertyCharacterSessionsStarted()
    {
    }

    /**
     * Test attribute "combat_cap_drainedby_npc"
     */
    public function testPropertyCombatCapDrainedbyNpc()
    {
    }

    /**
     * Test attribute "combat_cap_drainedby_pc"
     */
    public function testPropertyCombatCapDrainedbyPc()
    {
    }

    /**
     * Test attribute "combat_cap_draining_pc"
     */
    public function testPropertyCombatCapDrainingPc()
    {
    }

    /**
     * Test attribute "combat_criminal_flag_set"
     */
    public function testPropertyCombatCriminalFlagSet()
    {
    }

    /**
     * Test attribute "combat_damage_from_np_cs_amount"
     */
    public function testPropertyCombatDamageFromNpCsAmount()
    {
    }

    /**
     * Test attribute "combat_damage_from_np_cs_num_shots"
     */
    public function testPropertyCombatDamageFromNpCsNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_from_players_bomb_amount"
     */
    public function testPropertyCombatDamageFromPlayersBombAmount()
    {
    }

    /**
     * Test attribute "combat_damage_from_players_bomb_num_shots"
     */
    public function testPropertyCombatDamageFromPlayersBombNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_from_players_combat_drone_amount"
     */
    public function testPropertyCombatDamageFromPlayersCombatDroneAmount()
    {
    }

    /**
     * Test attribute "combat_damage_from_players_combat_drone_num_shots"
     */
    public function testPropertyCombatDamageFromPlayersCombatDroneNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_from_players_energy_amount"
     */
    public function testPropertyCombatDamageFromPlayersEnergyAmount()
    {
    }

    /**
     * Test attribute "combat_damage_from_players_energy_num_shots"
     */
    public function testPropertyCombatDamageFromPlayersEnergyNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_from_players_fighter_bomber_amount"
     */
    public function testPropertyCombatDamageFromPlayersFighterBomberAmount()
    {
    }

    /**
     * Test attribute "combat_damage_from_players_fighter_bomber_num_shots"
     */
    public function testPropertyCombatDamageFromPlayersFighterBomberNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_from_players_fighter_drone_amount"
     */
    public function testPropertyCombatDamageFromPlayersFighterDroneAmount()
    {
    }

    /**
     * Test attribute "combat_damage_from_players_fighter_drone_num_shots"
     */
    public function testPropertyCombatDamageFromPlayersFighterDroneNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_from_players_hybrid_amount"
     */
    public function testPropertyCombatDamageFromPlayersHybridAmount()
    {
    }

    /**
     * Test attribute "combat_damage_from_players_hybrid_num_shots"
     */
    public function testPropertyCombatDamageFromPlayersHybridNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_from_players_missile_amount"
     */
    public function testPropertyCombatDamageFromPlayersMissileAmount()
    {
    }

    /**
     * Test attribute "combat_damage_from_players_missile_num_shots"
     */
    public function testPropertyCombatDamageFromPlayersMissileNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_from_players_projectile_amount"
     */
    public function testPropertyCombatDamageFromPlayersProjectileAmount()
    {
    }

    /**
     * Test attribute "combat_damage_from_players_projectile_num_shots"
     */
    public function testPropertyCombatDamageFromPlayersProjectileNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_from_players_smart_bomb_amount"
     */
    public function testPropertyCombatDamageFromPlayersSmartBombAmount()
    {
    }

    /**
     * Test attribute "combat_damage_from_players_smart_bomb_num_shots"
     */
    public function testPropertyCombatDamageFromPlayersSmartBombNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_from_players_super_amount"
     */
    public function testPropertyCombatDamageFromPlayersSuperAmount()
    {
    }

    /**
     * Test attribute "combat_damage_from_players_super_num_shots"
     */
    public function testPropertyCombatDamageFromPlayersSuperNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_from_structures_total_amount"
     */
    public function testPropertyCombatDamageFromStructuresTotalAmount()
    {
    }

    /**
     * Test attribute "combat_damage_from_structures_total_num_shots"
     */
    public function testPropertyCombatDamageFromStructuresTotalNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_to_players_bomb_amount"
     */
    public function testPropertyCombatDamageToPlayersBombAmount()
    {
    }

    /**
     * Test attribute "combat_damage_to_players_bomb_num_shots"
     */
    public function testPropertyCombatDamageToPlayersBombNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_to_players_combat_drone_amount"
     */
    public function testPropertyCombatDamageToPlayersCombatDroneAmount()
    {
    }

    /**
     * Test attribute "combat_damage_to_players_combat_drone_num_shots"
     */
    public function testPropertyCombatDamageToPlayersCombatDroneNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_to_players_energy_amount"
     */
    public function testPropertyCombatDamageToPlayersEnergyAmount()
    {
    }

    /**
     * Test attribute "combat_damage_to_players_energy_num_shots"
     */
    public function testPropertyCombatDamageToPlayersEnergyNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_to_players_fighter_bomber_amount"
     */
    public function testPropertyCombatDamageToPlayersFighterBomberAmount()
    {
    }

    /**
     * Test attribute "combat_damage_to_players_fighter_bomber_num_shots"
     */
    public function testPropertyCombatDamageToPlayersFighterBomberNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_to_players_fighter_drone_amount"
     */
    public function testPropertyCombatDamageToPlayersFighterDroneAmount()
    {
    }

    /**
     * Test attribute "combat_damage_to_players_fighter_drone_num_shots"
     */
    public function testPropertyCombatDamageToPlayersFighterDroneNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_to_players_hybrid_amount"
     */
    public function testPropertyCombatDamageToPlayersHybridAmount()
    {
    }

    /**
     * Test attribute "combat_damage_to_players_hybrid_num_shots"
     */
    public function testPropertyCombatDamageToPlayersHybridNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_to_players_missile_amount"
     */
    public function testPropertyCombatDamageToPlayersMissileAmount()
    {
    }

    /**
     * Test attribute "combat_damage_to_players_missile_num_shots"
     */
    public function testPropertyCombatDamageToPlayersMissileNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_to_players_projectile_amount"
     */
    public function testPropertyCombatDamageToPlayersProjectileAmount()
    {
    }

    /**
     * Test attribute "combat_damage_to_players_projectile_num_shots"
     */
    public function testPropertyCombatDamageToPlayersProjectileNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_to_players_smart_bomb_amount"
     */
    public function testPropertyCombatDamageToPlayersSmartBombAmount()
    {
    }

    /**
     * Test attribute "combat_damage_to_players_smart_bomb_num_shots"
     */
    public function testPropertyCombatDamageToPlayersSmartBombNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_to_players_super_amount"
     */
    public function testPropertyCombatDamageToPlayersSuperAmount()
    {
    }

    /**
     * Test attribute "combat_damage_to_players_super_num_shots"
     */
    public function testPropertyCombatDamageToPlayersSuperNumShots()
    {
    }

    /**
     * Test attribute "combat_damage_to_structures_total_amount"
     */
    public function testPropertyCombatDamageToStructuresTotalAmount()
    {
    }

    /**
     * Test attribute "combat_damage_to_structures_total_num_shots"
     */
    public function testPropertyCombatDamageToStructuresTotalNumShots()
    {
    }

    /**
     * Test attribute "combat_deaths_high_sec"
     */
    public function testPropertyCombatDeathsHighSec()
    {
    }

    /**
     * Test attribute "combat_deaths_low_sec"
     */
    public function testPropertyCombatDeathsLowSec()
    {
    }

    /**
     * Test attribute "combat_deaths_null_sec"
     */
    public function testPropertyCombatDeathsNullSec()
    {
    }

    /**
     * Test attribute "combat_deaths_pod_high_sec"
     */
    public function testPropertyCombatDeathsPodHighSec()
    {
    }

    /**
     * Test attribute "combat_deaths_pod_low_sec"
     */
    public function testPropertyCombatDeathsPodLowSec()
    {
    }

    /**
     * Test attribute "combat_deaths_pod_null_sec"
     */
    public function testPropertyCombatDeathsPodNullSec()
    {
    }

    /**
     * Test attribute "combat_deaths_pod_wormhole"
     */
    public function testPropertyCombatDeathsPodWormhole()
    {
    }

    /**
     * Test attribute "combat_deaths_wormhole"
     */
    public function testPropertyCombatDeathsWormhole()
    {
    }

    /**
     * Test attribute "combat_drone_engage"
     */
    public function testPropertyCombatDroneEngage()
    {
    }

    /**
     * Test attribute "combat_duel_requested"
     */
    public function testPropertyCombatDuelRequested()
    {
    }

    /**
     * Test attribute "combat_engagement_register"
     */
    public function testPropertyCombatEngagementRegister()
    {
    }

    /**
     * Test attribute "combat_kills_assists"
     */
    public function testPropertyCombatKillsAssists()
    {
    }

    /**
     * Test attribute "combat_kills_high_sec"
     */
    public function testPropertyCombatKillsHighSec()
    {
    }

    /**
     * Test attribute "combat_kills_low_sec"
     */
    public function testPropertyCombatKillsLowSec()
    {
    }

    /**
     * Test attribute "combat_kills_null_sec"
     */
    public function testPropertyCombatKillsNullSec()
    {
    }

    /**
     * Test attribute "combat_kills_pod_high_sec"
     */
    public function testPropertyCombatKillsPodHighSec()
    {
    }

    /**
     * Test attribute "combat_kills_pod_low_sec"
     */
    public function testPropertyCombatKillsPodLowSec()
    {
    }

    /**
     * Test attribute "combat_kills_pod_null_sec"
     */
    public function testPropertyCombatKillsPodNullSec()
    {
    }

    /**
     * Test attribute "combat_kills_pod_wormhole"
     */
    public function testPropertyCombatKillsPodWormhole()
    {
    }

    /**
     * Test attribute "combat_kills_wormhole"
     */
    public function testPropertyCombatKillsWormhole()
    {
    }

    /**
     * Test attribute "combat_npc_flag_set"
     */
    public function testPropertyCombatNpcFlagSet()
    {
    }

    /**
     * Test attribute "combat_pvp_flag_set"
     */
    public function testPropertyCombatPvpFlagSet()
    {
    }

    /**
     * Test attribute "combat_repair_armor_by_remote_amount"
     */
    public function testPropertyCombatRepairArmorByRemoteAmount()
    {
    }

    /**
     * Test attribute "combat_repair_armor_remote_amount"
     */
    public function testPropertyCombatRepairArmorRemoteAmount()
    {
    }

    /**
     * Test attribute "combat_repair_armor_self_amount"
     */
    public function testPropertyCombatRepairArmorSelfAmount()
    {
    }

    /**
     * Test attribute "combat_repair_capacitor_by_remote_amount"
     */
    public function testPropertyCombatRepairCapacitorByRemoteAmount()
    {
    }

    /**
     * Test attribute "combat_repair_capacitor_remote_amount"
     */
    public function testPropertyCombatRepairCapacitorRemoteAmount()
    {
    }

    /**
     * Test attribute "combat_repair_capacitor_self_amount"
     */
    public function testPropertyCombatRepairCapacitorSelfAmount()
    {
    }

    /**
     * Test attribute "combat_repair_hull_by_remote_amount"
     */
    public function testPropertyCombatRepairHullByRemoteAmount()
    {
    }

    /**
     * Test attribute "combat_repair_hull_remote_amount"
     */
    public function testPropertyCombatRepairHullRemoteAmount()
    {
    }

    /**
     * Test attribute "combat_repair_hull_self_amount"
     */
    public function testPropertyCombatRepairHullSelfAmount()
    {
    }

    /**
     * Test attribute "combat_repair_shield_by_remote_amount"
     */
    public function testPropertyCombatRepairShieldByRemoteAmount()
    {
    }

    /**
     * Test attribute "combat_repair_shield_remote_amount"
     */
    public function testPropertyCombatRepairShieldRemoteAmount()
    {
    }

    /**
     * Test attribute "combat_repair_shield_self_amount"
     */
    public function testPropertyCombatRepairShieldSelfAmount()
    {
    }

    /**
     * Test attribute "combat_self_destructs"
     */
    public function testPropertyCombatSelfDestructs()
    {
    }

    /**
     * Test attribute "combat_warp_scramble_pc"
     */
    public function testPropertyCombatWarpScramblePc()
    {
    }

    /**
     * Test attribute "combat_warp_scrambledby_npc"
     */
    public function testPropertyCombatWarpScrambledbyNpc()
    {
    }

    /**
     * Test attribute "combat_warp_scrambledby_pc"
     */
    public function testPropertyCombatWarpScrambledbyPc()
    {
    }

    /**
     * Test attribute "combat_weapon_flag_set"
     */
    public function testPropertyCombatWeaponFlagSet()
    {
    }

    /**
     * Test attribute "combat_webifiedby_npc"
     */
    public function testPropertyCombatWebifiedbyNpc()
    {
    }

    /**
     * Test attribute "combat_webifiedby_pc"
     */
    public function testPropertyCombatWebifiedbyPc()
    {
    }

    /**
     * Test attribute "combat_webifying_pc"
     */
    public function testPropertyCombatWebifyingPc()
    {
    }

    /**
     * Test attribute "days_of_activity"
     */
    public function testPropertyDaysOfActivity()
    {
    }

    /**
     * Test attribute "generic_cone_scans"
     */
    public function testPropertyGenericConeScans()
    {
    }

    /**
     * Test attribute "generic_request_scans"
     */
    public function testPropertyGenericRequestScans()
    {
    }

    /**
     * Test attribute "industry_hacking_successes"
     */
    public function testPropertyIndustryHackingSuccesses()
    {
    }

    /**
     * Test attribute "industry_jobs_cancelled"
     */
    public function testPropertyIndustryJobsCancelled()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_copy_blueprint"
     */
    public function testPropertyIndustryJobsCompletedCopyBlueprint()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_invention"
     */
    public function testPropertyIndustryJobsCompletedInvention()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture"
     */
    public function testPropertyIndustryJobsCompletedManufacture()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_asteroid"
     */
    public function testPropertyIndustryJobsCompletedManufactureAsteroid()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_asteroid_quantity"
     */
    public function testPropertyIndustryJobsCompletedManufactureAsteroidQuantity()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_charge"
     */
    public function testPropertyIndustryJobsCompletedManufactureCharge()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_charge_quantity"
     */
    public function testPropertyIndustryJobsCompletedManufactureChargeQuantity()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_commodity"
     */
    public function testPropertyIndustryJobsCompletedManufactureCommodity()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_commodity_quantity"
     */
    public function testPropertyIndustryJobsCompletedManufactureCommodityQuantity()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_deployable"
     */
    public function testPropertyIndustryJobsCompletedManufactureDeployable()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_deployable_quantity"
     */
    public function testPropertyIndustryJobsCompletedManufactureDeployableQuantity()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_drone"
     */
    public function testPropertyIndustryJobsCompletedManufactureDrone()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_drone_quantity"
     */
    public function testPropertyIndustryJobsCompletedManufactureDroneQuantity()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_implant"
     */
    public function testPropertyIndustryJobsCompletedManufactureImplant()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_implant_quantity"
     */
    public function testPropertyIndustryJobsCompletedManufactureImplantQuantity()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_module"
     */
    public function testPropertyIndustryJobsCompletedManufactureModule()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_module_quantity"
     */
    public function testPropertyIndustryJobsCompletedManufactureModuleQuantity()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_other"
     */
    public function testPropertyIndustryJobsCompletedManufactureOther()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_other_quantity"
     */
    public function testPropertyIndustryJobsCompletedManufactureOtherQuantity()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_ship"
     */
    public function testPropertyIndustryJobsCompletedManufactureShip()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_ship_quantity"
     */
    public function testPropertyIndustryJobsCompletedManufactureShipQuantity()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_structure"
     */
    public function testPropertyIndustryJobsCompletedManufactureStructure()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_structure_quantity"
     */
    public function testPropertyIndustryJobsCompletedManufactureStructureQuantity()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_subsystem"
     */
    public function testPropertyIndustryJobsCompletedManufactureSubsystem()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_manufacture_subsystem_quantity"
     */
    public function testPropertyIndustryJobsCompletedManufactureSubsystemQuantity()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_material_productivity"
     */
    public function testPropertyIndustryJobsCompletedMaterialProductivity()
    {
    }

    /**
     * Test attribute "industry_jobs_completed_time_productivity"
     */
    public function testPropertyIndustryJobsCompletedTimeProductivity()
    {
    }

    /**
     * Test attribute "industry_jobs_started_copy_blueprint"
     */
    public function testPropertyIndustryJobsStartedCopyBlueprint()
    {
    }

    /**
     * Test attribute "industry_jobs_started_invention"
     */
    public function testPropertyIndustryJobsStartedInvention()
    {
    }

    /**
     * Test attribute "industry_jobs_started_manufacture"
     */
    public function testPropertyIndustryJobsStartedManufacture()
    {
    }

    /**
     * Test attribute "industry_jobs_started_material_productivity"
     */
    public function testPropertyIndustryJobsStartedMaterialProductivity()
    {
    }

    /**
     * Test attribute "industry_jobs_started_time_productivity"
     */
    public function testPropertyIndustryJobsStartedTimeProductivity()
    {
    }

    /**
     * Test attribute "industry_reprocess_item"
     */
    public function testPropertyIndustryReprocessItem()
    {
    }

    /**
     * Test attribute "industry_reprocess_item_quantity"
     */
    public function testPropertyIndustryReprocessItemQuantity()
    {
    }

    /**
     * Test attribute "inventory_abandon_loot_quantity"
     */
    public function testPropertyInventoryAbandonLootQuantity()
    {
    }

    /**
     * Test attribute "inventory_trash_item_quantity"
     */
    public function testPropertyInventoryTrashItemQuantity()
    {
    }

    /**
     * Test attribute "isk_in"
     */
    public function testPropertyIskIn()
    {
    }

    /**
     * Test attribute "isk_out"
     */
    public function testPropertyIskOut()
    {
    }

    /**
     * Test attribute "market_accept_contracts_courier"
     */
    public function testPropertyMarketAcceptContractsCourier()
    {
    }

    /**
     * Test attribute "market_accept_contracts_item_exchange"
     */
    public function testPropertyMarketAcceptContractsItemExchange()
    {
    }

    /**
     * Test attribute "market_buy_orders_placed"
     */
    public function testPropertyMarketBuyOrdersPlaced()
    {
    }

    /**
     * Test attribute "market_cancel_market_order"
     */
    public function testPropertyMarketCancelMarketOrder()
    {
    }

    /**
     * Test attribute "market_create_contracts_auction"
     */
    public function testPropertyMarketCreateContractsAuction()
    {
    }

    /**
     * Test attribute "market_create_contracts_courier"
     */
    public function testPropertyMarketCreateContractsCourier()
    {
    }

    /**
     * Test attribute "market_create_contracts_item_exchange"
     */
    public function testPropertyMarketCreateContractsItemExchange()
    {
    }

    /**
     * Test attribute "market_deliver_courier_contract"
     */
    public function testPropertyMarketDeliverCourierContract()
    {
    }

    /**
     * Test attribute "market_isk_gained"
     */
    public function testPropertyMarketIskGained()
    {
    }

    /**
     * Test attribute "market_isk_spent"
     */
    public function testPropertyMarketIskSpent()
    {
    }

    /**
     * Test attribute "market_modify_market_order"
     */
    public function testPropertyMarketModifyMarketOrder()
    {
    }

    /**
     * Test attribute "market_search_contracts"
     */
    public function testPropertyMarketSearchContracts()
    {
    }

    /**
     * Test attribute "market_sell_orders_placed"
     */
    public function testPropertyMarketSellOrdersPlaced()
    {
    }

    /**
     * Test attribute "mining_drone_mine"
     */
    public function testPropertyMiningDroneMine()
    {
    }

    /**
     * Test attribute "mining_ore_arkonor"
     */
    public function testPropertyMiningOreArkonor()
    {
    }

    /**
     * Test attribute "mining_ore_bistot"
     */
    public function testPropertyMiningOreBistot()
    {
    }

    /**
     * Test attribute "mining_ore_crokite"
     */
    public function testPropertyMiningOreCrokite()
    {
    }

    /**
     * Test attribute "mining_ore_dark_ochre"
     */
    public function testPropertyMiningOreDarkOchre()
    {
    }

    /**
     * Test attribute "mining_ore_gneiss"
     */
    public function testPropertyMiningOreGneiss()
    {
    }

    /**
     * Test attribute "mining_ore_harvestable_cloud"
     */
    public function testPropertyMiningOreHarvestableCloud()
    {
    }

    /**
     * Test attribute "mining_ore_hedbergite"
     */
    public function testPropertyMiningOreHedbergite()
    {
    }

    /**
     * Test attribute "mining_ore_hemorphite"
     */
    public function testPropertyMiningOreHemorphite()
    {
    }

    /**
     * Test attribute "mining_ore_ice"
     */
    public function testPropertyMiningOreIce()
    {
    }

    /**
     * Test attribute "mining_ore_jaspet"
     */
    public function testPropertyMiningOreJaspet()
    {
    }

    /**
     * Test attribute "mining_ore_kernite"
     */
    public function testPropertyMiningOreKernite()
    {
    }

    /**
     * Test attribute "mining_ore_mercoxit"
     */
    public function testPropertyMiningOreMercoxit()
    {
    }

    /**
     * Test attribute "mining_ore_omber"
     */
    public function testPropertyMiningOreOmber()
    {
    }

    /**
     * Test attribute "mining_ore_plagioclase"
     */
    public function testPropertyMiningOrePlagioclase()
    {
    }

    /**
     * Test attribute "mining_ore_pyroxeres"
     */
    public function testPropertyMiningOrePyroxeres()
    {
    }

    /**
     * Test attribute "mining_ore_scordite"
     */
    public function testPropertyMiningOreScordite()
    {
    }

    /**
     * Test attribute "mining_ore_spodumain"
     */
    public function testPropertyMiningOreSpodumain()
    {
    }

    /**
     * Test attribute "mining_ore_veldspar"
     */
    public function testPropertyMiningOreVeldspar()
    {
    }

    /**
     * Test attribute "module_activations_armor_hardener"
     */
    public function testPropertyModuleActivationsArmorHardener()
    {
    }

    /**
     * Test attribute "module_activations_armor_repair_unit"
     */
    public function testPropertyModuleActivationsArmorRepairUnit()
    {
    }

    /**
     * Test attribute "module_activations_armor_resistance_shift_hardener"
     */
    public function testPropertyModuleActivationsArmorResistanceShiftHardener()
    {
    }

    /**
     * Test attribute "module_activations_automated_targeting_system"
     */
    public function testPropertyModuleActivationsAutomatedTargetingSystem()
    {
    }

    /**
     * Test attribute "module_activations_bastion"
     */
    public function testPropertyModuleActivationsBastion()
    {
    }

    /**
     * Test attribute "module_activations_bomb_launcher"
     */
    public function testPropertyModuleActivationsBombLauncher()
    {
    }

    /**
     * Test attribute "module_activations_capacitor_booster"
     */
    public function testPropertyModuleActivationsCapacitorBooster()
    {
    }

    /**
     * Test attribute "module_activations_cargo_scanner"
     */
    public function testPropertyModuleActivationsCargoScanner()
    {
    }

    /**
     * Test attribute "module_activations_cloaking_device"
     */
    public function testPropertyModuleActivationsCloakingDevice()
    {
    }

    /**
     * Test attribute "module_activations_clone_vat_bay"
     */
    public function testPropertyModuleActivationsCloneVatBay()
    {
    }

    /**
     * Test attribute "module_activations_cynosural_field"
     */
    public function testPropertyModuleActivationsCynosuralField()
    {
    }

    /**
     * Test attribute "module_activations_damage_control"
     */
    public function testPropertyModuleActivationsDamageControl()
    {
    }

    /**
     * Test attribute "module_activations_data_miners"
     */
    public function testPropertyModuleActivationsDataMiners()
    {
    }

    /**
     * Test attribute "module_activations_drone_control_unit"
     */
    public function testPropertyModuleActivationsDroneControlUnit()
    {
    }

    /**
     * Test attribute "module_activations_drone_tracking_modules"
     */
    public function testPropertyModuleActivationsDroneTrackingModules()
    {
    }

    /**
     * Test attribute "module_activations_eccm"
     */
    public function testPropertyModuleActivationsEccm()
    {
    }

    /**
     * Test attribute "module_activations_ecm"
     */
    public function testPropertyModuleActivationsEcm()
    {
    }

    /**
     * Test attribute "module_activations_ecm_burst"
     */
    public function testPropertyModuleActivationsEcmBurst()
    {
    }

    /**
     * Test attribute "module_activations_energy_destabilizer"
     */
    public function testPropertyModuleActivationsEnergyDestabilizer()
    {
    }

    /**
     * Test attribute "module_activations_energy_vampire"
     */
    public function testPropertyModuleActivationsEnergyVampire()
    {
    }

    /**
     * Test attribute "module_activations_energy_weapon"
     */
    public function testPropertyModuleActivationsEnergyWeapon()
    {
    }

    /**
     * Test attribute "module_activations_festival_launcher"
     */
    public function testPropertyModuleActivationsFestivalLauncher()
    {
    }

    /**
     * Test attribute "module_activations_frequency_mining_laser"
     */
    public function testPropertyModuleActivationsFrequencyMiningLaser()
    {
    }

    /**
     * Test attribute "module_activations_fueled_armor_repairer"
     */
    public function testPropertyModuleActivationsFueledArmorRepairer()
    {
    }

    /**
     * Test attribute "module_activations_fueled_shield_booster"
     */
    public function testPropertyModuleActivationsFueledShieldBooster()
    {
    }

    /**
     * Test attribute "module_activations_gang_coordinator"
     */
    public function testPropertyModuleActivationsGangCoordinator()
    {
    }

    /**
     * Test attribute "module_activations_gas_cloud_harvester"
     */
    public function testPropertyModuleActivationsGasCloudHarvester()
    {
    }

    /**
     * Test attribute "module_activations_hull_repair_unit"
     */
    public function testPropertyModuleActivationsHullRepairUnit()
    {
    }

    /**
     * Test attribute "module_activations_hybrid_weapon"
     */
    public function testPropertyModuleActivationsHybridWeapon()
    {
    }

    /**
     * Test attribute "module_activations_industrial_core"
     */
    public function testPropertyModuleActivationsIndustrialCore()
    {
    }

    /**
     * Test attribute "module_activations_interdiction_sphere_launcher"
     */
    public function testPropertyModuleActivationsInterdictionSphereLauncher()
    {
    }

    /**
     * Test attribute "module_activations_micro_jump_drive"
     */
    public function testPropertyModuleActivationsMicroJumpDrive()
    {
    }

    /**
     * Test attribute "module_activations_mining_laser"
     */
    public function testPropertyModuleActivationsMiningLaser()
    {
    }

    /**
     * Test attribute "module_activations_missile_launcher"
     */
    public function testPropertyModuleActivationsMissileLauncher()
    {
    }

    /**
     * Test attribute "module_activations_passive_targeting_system"
     */
    public function testPropertyModuleActivationsPassiveTargetingSystem()
    {
    }

    /**
     * Test attribute "module_activations_probe_launcher"
     */
    public function testPropertyModuleActivationsProbeLauncher()
    {
    }

    /**
     * Test attribute "module_activations_projected_eccm"
     */
    public function testPropertyModuleActivationsProjectedEccm()
    {
    }

    /**
     * Test attribute "module_activations_projectile_weapon"
     */
    public function testPropertyModuleActivationsProjectileWeapon()
    {
    }

    /**
     * Test attribute "module_activations_propulsion_module"
     */
    public function testPropertyModuleActivationsPropulsionModule()
    {
    }

    /**
     * Test attribute "module_activations_remote_armor_repairer"
     */
    public function testPropertyModuleActivationsRemoteArmorRepairer()
    {
    }

    /**
     * Test attribute "module_activations_remote_capacitor_transmitter"
     */
    public function testPropertyModuleActivationsRemoteCapacitorTransmitter()
    {
    }

    /**
     * Test attribute "module_activations_remote_ecm_burst"
     */
    public function testPropertyModuleActivationsRemoteEcmBurst()
    {
    }

    /**
     * Test attribute "module_activations_remote_hull_repairer"
     */
    public function testPropertyModuleActivationsRemoteHullRepairer()
    {
    }

    /**
     * Test attribute "module_activations_remote_sensor_booster"
     */
    public function testPropertyModuleActivationsRemoteSensorBooster()
    {
    }

    /**
     * Test attribute "module_activations_remote_sensor_damper"
     */
    public function testPropertyModuleActivationsRemoteSensorDamper()
    {
    }

    /**
     * Test attribute "module_activations_remote_shield_booster"
     */
    public function testPropertyModuleActivationsRemoteShieldBooster()
    {
    }

    /**
     * Test attribute "module_activations_remote_tracking_computer"
     */
    public function testPropertyModuleActivationsRemoteTrackingComputer()
    {
    }

    /**
     * Test attribute "module_activations_salvager"
     */
    public function testPropertyModuleActivationsSalvager()
    {
    }

    /**
     * Test attribute "module_activations_sensor_booster"
     */
    public function testPropertyModuleActivationsSensorBooster()
    {
    }

    /**
     * Test attribute "module_activations_shield_booster"
     */
    public function testPropertyModuleActivationsShieldBooster()
    {
    }

    /**
     * Test attribute "module_activations_shield_hardener"
     */
    public function testPropertyModuleActivationsShieldHardener()
    {
    }

    /**
     * Test attribute "module_activations_ship_scanner"
     */
    public function testPropertyModuleActivationsShipScanner()
    {
    }

    /**
     * Test attribute "module_activations_siege"
     */
    public function testPropertyModuleActivationsSiege()
    {
    }

    /**
     * Test attribute "module_activations_smart_bomb"
     */
    public function testPropertyModuleActivationsSmartBomb()
    {
    }

    /**
     * Test attribute "module_activations_stasis_web"
     */
    public function testPropertyModuleActivationsStasisWeb()
    {
    }

    /**
     * Test attribute "module_activations_strip_miner"
     */
    public function testPropertyModuleActivationsStripMiner()
    {
    }

    /**
     * Test attribute "module_activations_super_weapon"
     */
    public function testPropertyModuleActivationsSuperWeapon()
    {
    }

    /**
     * Test attribute "module_activations_survey_scanner"
     */
    public function testPropertyModuleActivationsSurveyScanner()
    {
    }

    /**
     * Test attribute "module_activations_target_breaker"
     */
    public function testPropertyModuleActivationsTargetBreaker()
    {
    }

    /**
     * Test attribute "module_activations_target_painter"
     */
    public function testPropertyModuleActivationsTargetPainter()
    {
    }

    /**
     * Test attribute "module_activations_tracking_computer"
     */
    public function testPropertyModuleActivationsTrackingComputer()
    {
    }

    /**
     * Test attribute "module_activations_tracking_disruptor"
     */
    public function testPropertyModuleActivationsTrackingDisruptor()
    {
    }

    /**
     * Test attribute "module_activations_tractor_beam"
     */
    public function testPropertyModuleActivationsTractorBeam()
    {
    }

    /**
     * Test attribute "module_activations_triage"
     */
    public function testPropertyModuleActivationsTriage()
    {
    }

    /**
     * Test attribute "module_activations_warp_disrupt_field_generator"
     */
    public function testPropertyModuleActivationsWarpDisruptFieldGenerator()
    {
    }

    /**
     * Test attribute "module_activations_warp_scrambler"
     */
    public function testPropertyModuleActivationsWarpScrambler()
    {
    }

    /**
     * Test attribute "module_link_weapons"
     */
    public function testPropertyModuleLinkWeapons()
    {
    }

    /**
     * Test attribute "module_overload"
     */
    public function testPropertyModuleOverload()
    {
    }

    /**
     * Test attribute "module_repairs"
     */
    public function testPropertyModuleRepairs()
    {
    }

    /**
     * Test attribute "orbital_strike_characters_killed"
     */
    public function testPropertyOrbitalStrikeCharactersKilled()
    {
    }

    /**
     * Test attribute "orbital_strike_damage_to_players_armor_amount"
     */
    public function testPropertyOrbitalStrikeDamageToPlayersArmorAmount()
    {
    }

    /**
     * Test attribute "orbital_strike_damage_to_players_shield_amount"
     */
    public function testPropertyOrbitalStrikeDamageToPlayersShieldAmount()
    {
    }

    /**
     * Test attribute "pve_dungeons_completed_agent"
     */
    public function testPropertyPveDungeonsCompletedAgent()
    {
    }

    /**
     * Test attribute "pve_dungeons_completed_distribution"
     */
    public function testPropertyPveDungeonsCompletedDistribution()
    {
    }

    /**
     * Test attribute "pve_missions_succeeded"
     */
    public function testPropertyPveMissionsSucceeded()
    {
    }

    /**
     * Test attribute "pve_missions_succeeded_epic_arc"
     */
    public function testPropertyPveMissionsSucceededEpicArc()
    {
    }

    /**
     * Test attribute "social_add_contact_bad"
     */
    public function testPropertySocialAddContactBad()
    {
    }

    /**
     * Test attribute "social_add_contact_good"
     */
    public function testPropertySocialAddContactGood()
    {
    }

    /**
     * Test attribute "social_add_contact_high"
     */
    public function testPropertySocialAddContactHigh()
    {
    }

    /**
     * Test attribute "social_add_contact_horrible"
     */
    public function testPropertySocialAddContactHorrible()
    {
    }

    /**
     * Test attribute "social_add_contact_neutral"
     */
    public function testPropertySocialAddContactNeutral()
    {
    }

    /**
     * Test attribute "social_add_note"
     */
    public function testPropertySocialAddNote()
    {
    }

    /**
     * Test attribute "social_added_as_contact_bad"
     */
    public function testPropertySocialAddedAsContactBad()
    {
    }

    /**
     * Test attribute "social_added_as_contact_good"
     */
    public function testPropertySocialAddedAsContactGood()
    {
    }

    /**
     * Test attribute "social_added_as_contact_high"
     */
    public function testPropertySocialAddedAsContactHigh()
    {
    }

    /**
     * Test attribute "social_added_as_contact_horrible"
     */
    public function testPropertySocialAddedAsContactHorrible()
    {
    }

    /**
     * Test attribute "social_added_as_contact_neutral"
     */
    public function testPropertySocialAddedAsContactNeutral()
    {
    }

    /**
     * Test attribute "social_calendar_event_created"
     */
    public function testPropertySocialCalendarEventCreated()
    {
    }

    /**
     * Test attribute "social_chat_messages_alliance"
     */
    public function testPropertySocialChatMessagesAlliance()
    {
    }

    /**
     * Test attribute "social_chat_messages_constellation"
     */
    public function testPropertySocialChatMessagesConstellation()
    {
    }

    /**
     * Test attribute "social_chat_messages_corporation"
     */
    public function testPropertySocialChatMessagesCorporation()
    {
    }

    /**
     * Test attribute "social_chat_messages_fleet"
     */
    public function testPropertySocialChatMessagesFleet()
    {
    }

    /**
     * Test attribute "social_chat_messages_region"
     */
    public function testPropertySocialChatMessagesRegion()
    {
    }

    /**
     * Test attribute "social_chat_messages_solarsystem"
     */
    public function testPropertySocialChatMessagesSolarsystem()
    {
    }

    /**
     * Test attribute "social_chat_messages_warfaction"
     */
    public function testPropertySocialChatMessagesWarfaction()
    {
    }

    /**
     * Test attribute "social_chat_total_message_length"
     */
    public function testPropertySocialChatTotalMessageLength()
    {
    }

    /**
     * Test attribute "social_direct_trades"
     */
    public function testPropertySocialDirectTrades()
    {
    }

    /**
     * Test attribute "social_fleet_broadcasts"
     */
    public function testPropertySocialFleetBroadcasts()
    {
    }

    /**
     * Test attribute "social_fleet_joins"
     */
    public function testPropertySocialFleetJoins()
    {
    }

    /**
     * Test attribute "social_mails_received"
     */
    public function testPropertySocialMailsReceived()
    {
    }

    /**
     * Test attribute "social_mails_sent"
     */
    public function testPropertySocialMailsSent()
    {
    }

    /**
     * Test attribute "travel_acceleration_gate_activations"
     */
    public function testPropertyTravelAccelerationGateActivations()
    {
    }

    /**
     * Test attribute "travel_align_to"
     */
    public function testPropertyTravelAlignTo()
    {
    }

    /**
     * Test attribute "travel_distance_warped_high_sec"
     */
    public function testPropertyTravelDistanceWarpedHighSec()
    {
    }

    /**
     * Test attribute "travel_distance_warped_low_sec"
     */
    public function testPropertyTravelDistanceWarpedLowSec()
    {
    }

    /**
     * Test attribute "travel_distance_warped_null_sec"
     */
    public function testPropertyTravelDistanceWarpedNullSec()
    {
    }

    /**
     * Test attribute "travel_distance_warped_wormhole"
     */
    public function testPropertyTravelDistanceWarpedWormhole()
    {
    }

    /**
     * Test attribute "travel_docks_high_sec"
     */
    public function testPropertyTravelDocksHighSec()
    {
    }

    /**
     * Test attribute "travel_docks_low_sec"
     */
    public function testPropertyTravelDocksLowSec()
    {
    }

    /**
     * Test attribute "travel_docks_null_sec"
     */
    public function testPropertyTravelDocksNullSec()
    {
    }

    /**
     * Test attribute "travel_jumps_stargate_high_sec"
     */
    public function testPropertyTravelJumpsStargateHighSec()
    {
    }

    /**
     * Test attribute "travel_jumps_stargate_low_sec"
     */
    public function testPropertyTravelJumpsStargateLowSec()
    {
    }

    /**
     * Test attribute "travel_jumps_stargate_null_sec"
     */
    public function testPropertyTravelJumpsStargateNullSec()
    {
    }

    /**
     * Test attribute "travel_jumps_wormhole"
     */
    public function testPropertyTravelJumpsWormhole()
    {
    }

    /**
     * Test attribute "travel_warps_high_sec"
     */
    public function testPropertyTravelWarpsHighSec()
    {
    }

    /**
     * Test attribute "travel_warps_low_sec"
     */
    public function testPropertyTravelWarpsLowSec()
    {
    }

    /**
     * Test attribute "travel_warps_null_sec"
     */
    public function testPropertyTravelWarpsNullSec()
    {
    }

    /**
     * Test attribute "travel_warps_to_bookmark"
     */
    public function testPropertyTravelWarpsToBookmark()
    {
    }

    /**
     * Test attribute "travel_warps_to_celestial"
     */
    public function testPropertyTravelWarpsToCelestial()
    {
    }

    /**
     * Test attribute "travel_warps_to_fleet_member"
     */
    public function testPropertyTravelWarpsToFleetMember()
    {
    }

    /**
     * Test attribute "travel_warps_to_scan_result"
     */
    public function testPropertyTravelWarpsToScanResult()
    {
    }

    /**
     * Test attribute "travel_warps_wormhole"
     */
    public function testPropertyTravelWarpsWormhole()
    {
    }
}
