<?php
/**
 * GetAlliancesAllianceIdOkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * GetAlliancesAllianceIdOkTest Class Doc Comment
 *
 * @category    Class
 * @description 200 ok object
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetAlliancesAllianceIdOkTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetAlliancesAllianceIdOk"
     */
    public function testGetAlliancesAllianceIdOk()
    {
    }

    /**
     * Test attribute "creator_corporation_id"
     */
    public function testPropertyCreatorCorporationId()
    {
    }

    /**
     * Test attribute "creator_id"
     */
    public function testPropertyCreatorId()
    {
    }

    /**
     * Test attribute "date_founded"
     */
    public function testPropertyDateFounded()
    {
    }

    /**
     * Test attribute "executor_corporation_id"
     */
    public function testPropertyExecutorCorporationId()
    {
    }

    /**
     * Test attribute "faction_id"
     */
    public function testPropertyFactionId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "ticker"
     */
    public function testPropertyTicker()
    {
    }
}
