<?php
/**
 * GetCharactersCharacterIdPlanetsPlanetIdPinTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.19
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * GetCharactersCharacterIdPlanetsPlanetIdPinTest Class Doc Comment
 *
 * @category    Class
 * @description pin object
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetCharactersCharacterIdPlanetsPlanetIdPinTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetCharactersCharacterIdPlanetsPlanetIdPin"
     */
    public function testGetCharactersCharacterIdPlanetsPlanetIdPin()
    {
    }

    /**
     * Test attribute "contents"
     */
    public function testPropertyContents()
    {
    }

    /**
     * Test attribute "expiry_time"
     */
    public function testPropertyExpiryTime()
    {
    }

    /**
     * Test attribute "extractor_details"
     */
    public function testPropertyExtractorDetails()
    {
    }

    /**
     * Test attribute "factory_details"
     */
    public function testPropertyFactoryDetails()
    {
    }

    /**
     * Test attribute "install_time"
     */
    public function testPropertyInstallTime()
    {
    }

    /**
     * Test attribute "last_cycle_start"
     */
    public function testPropertyLastCycleStart()
    {
    }

    /**
     * Test attribute "latitude"
     */
    public function testPropertyLatitude()
    {
    }

    /**
     * Test attribute "longitude"
     */
    public function testPropertyLongitude()
    {
    }

    /**
     * Test attribute "pin_id"
     */
    public function testPropertyPinId()
    {
    }

    /**
     * Test attribute "schematic_id"
     */
    public function testPropertySchematicId()
    {
    }

    /**
     * Test attribute "type_id"
     */
    public function testPropertyTypeId()
    {
    }
}
