<?php
/**
 * GetCorporationsCorporationIdContainersLogs200OkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.19
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * GetCorporationsCorporationIdContainersLogs200OkTest Class Doc Comment
 *
 * @category    Class
 * @description 200 ok object
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetCorporationsCorporationIdContainersLogs200OkTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetCorporationsCorporationIdContainersLogs200Ok"
     */
    public function testGetCorporationsCorporationIdContainersLogs200Ok()
    {
    }

    /**
     * Test attribute "action"
     */
    public function testPropertyAction()
    {
    }

    /**
     * Test attribute "character_id"
     */
    public function testPropertyCharacterId()
    {
    }

    /**
     * Test attribute "container_id"
     */
    public function testPropertyContainerId()
    {
    }

    /**
     * Test attribute "container_type_id"
     */
    public function testPropertyContainerTypeId()
    {
    }

    /**
     * Test attribute "location_flag"
     */
    public function testPropertyLocationFlag()
    {
    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {
    }

    /**
     * Test attribute "logged_at"
     */
    public function testPropertyLoggedAt()
    {
    }

    /**
     * Test attribute "new_config_bitmask"
     */
    public function testPropertyNewConfigBitmask()
    {
    }

    /**
     * Test attribute "old_config_bitmask"
     */
    public function testPropertyOldConfigBitmask()
    {
    }

    /**
     * Test attribute "password_type"
     */
    public function testPropertyPasswordType()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "type_id"
     */
    public function testPropertyTypeId()
    {
    }
}
