<?php
/**
 * GetCharactersCharacterIdPlanetsPlanetIdExtractorDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.19
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * GetCharactersCharacterIdPlanetsPlanetIdExtractorDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description extractor_details object
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetCharactersCharacterIdPlanetsPlanetIdExtractorDetailsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails"
     */
    public function testGetCharactersCharacterIdPlanetsPlanetIdExtractorDetails()
    {
    }

    /**
     * Test attribute "cycle_time"
     */
    public function testPropertyCycleTime()
    {
    }

    /**
     * Test attribute "head_radius"
     */
    public function testPropertyHeadRadius()
    {
    }

    /**
     * Test attribute "heads"
     */
    public function testPropertyHeads()
    {
    }

    /**
     * Test attribute "product_type_id"
     */
    public function testPropertyProductTypeId()
    {
    }

    /**
     * Test attribute "qty_per_cycle"
     */
    public function testPropertyQtyPerCycle()
    {
    }
}
