<?php
/**
 * GetDogmaDynamicItemsTypeIdItemIdOkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.19
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * GetDogmaDynamicItemsTypeIdItemIdOkTest Class Doc Comment
 *
 * @category    Class
 * @description 200 ok object
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetDogmaDynamicItemsTypeIdItemIdOkTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetDogmaDynamicItemsTypeIdItemIdOk"
     */
    public function testGetDogmaDynamicItemsTypeIdItemIdOk()
    {
    }

    /**
     * Test attribute "created_by"
     */
    public function testPropertyCreatedBy()
    {
    }

    /**
     * Test attribute "dogma_attributes"
     */
    public function testPropertyDogmaAttributes()
    {
    }

    /**
     * Test attribute "dogma_effects"
     */
    public function testPropertyDogmaEffects()
    {
    }

    /**
     * Test attribute "mutator_type_id"
     */
    public function testPropertyMutatorTypeId()
    {
    }

    /**
     * Test attribute "source_type_id"
     */
    public function testPropertySourceTypeId()
    {
    }
}
