<?php
/**
 * GetFwLeaderboardsKillsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * GetFwLeaderboardsKillsTest Class Doc Comment
 *
 * @category    Class
 * @description Top 4 rankings of factions by number of kills from yesterday, last week and in total
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetFwLeaderboardsKillsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetFwLeaderboardsKills"
     */
    public function testGetFwLeaderboardsKills()
    {
    }

    /**
     * Test attribute "active_total"
     */
    public function testPropertyActiveTotal()
    {
    }

    /**
     * Test attribute "last_week"
     */
    public function testPropertyLastWeek()
    {
    }

    /**
     * Test attribute "yesterday"
     */
    public function testPropertyYesterday()
    {
    }
}
