<?php
/**
 * GetKillmailsKillmailIdKillmailHashAttackerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * GetKillmailsKillmailIdKillmailHashAttackerTest Class Doc Comment
 *
 * @category    Class
 * @description attacker object
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetKillmailsKillmailIdKillmailHashAttackerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetKillmailsKillmailIdKillmailHashAttacker"
     */
    public function testGetKillmailsKillmailIdKillmailHashAttacker()
    {
    }

    /**
     * Test attribute "alliance_id"
     */
    public function testPropertyAllianceId()
    {
    }

    /**
     * Test attribute "character_id"
     */
    public function testPropertyCharacterId()
    {
    }

    /**
     * Test attribute "corporation_id"
     */
    public function testPropertyCorporationId()
    {
    }

    /**
     * Test attribute "damage_done"
     */
    public function testPropertyDamageDone()
    {
    }

    /**
     * Test attribute "faction_id"
     */
    public function testPropertyFactionId()
    {
    }

    /**
     * Test attribute "final_blow"
     */
    public function testPropertyFinalBlow()
    {
    }

    /**
     * Test attribute "security_status"
     */
    public function testPropertySecurityStatus()
    {
    }

    /**
     * Test attribute "ship_type_id"
     */
    public function testPropertyShipTypeId()
    {
    }

    /**
     * Test attribute "weapon_type_id"
     */
    public function testPropertyWeaponTypeId()
    {
    }
}
