<?php
/**
 * GetSovereigntyStructures200OkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.19
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * GetSovereigntyStructures200OkTest Class Doc Comment
 *
 * @category    Class
 * @description 200 ok object
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetSovereigntyStructures200OkTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetSovereigntyStructures200Ok"
     */
    public function testGetSovereigntyStructures200Ok()
    {
    }

    /**
     * Test attribute "alliance_id"
     */
    public function testPropertyAllianceId()
    {
    }

    /**
     * Test attribute "solar_system_id"
     */
    public function testPropertySolarSystemId()
    {
    }

    /**
     * Test attribute "structure_id"
     */
    public function testPropertyStructureId()
    {
    }

    /**
     * Test attribute "structure_type_id"
     */
    public function testPropertyStructureTypeId()
    {
    }

    /**
     * Test attribute "vulnerability_occupancy_level"
     */
    public function testPropertyVulnerabilityOccupancyLevel()
    {
    }

    /**
     * Test attribute "vulnerable_end_time"
     */
    public function testPropertyVulnerableEndTime()
    {
    }

    /**
     * Test attribute "vulnerable_start_time"
     */
    public function testPropertyVulnerableStartTime()
    {
    }
}
