<?php
/**
 * GetUniverseSystemsSystemIdPlanetTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.19
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * GetUniverseSystemsSystemIdPlanetTest Class Doc Comment
 *
 * @category    Class
 * @description planet object
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetUniverseSystemsSystemIdPlanetTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetUniverseSystemsSystemIdPlanet"
     */
    public function testGetUniverseSystemsSystemIdPlanet()
    {
    }

    /**
     * Test attribute "asteroid_belts"
     */
    public function testPropertyAsteroidBelts()
    {
    }

    /**
     * Test attribute "moons"
     */
    public function testPropertyMoons()
    {
    }

    /**
     * Test attribute "planet_id"
     */
    public function testPropertyPlanetId()
    {
    }
}
