<?php
/**
 * GetWarsWarIdOkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * GetWarsWarIdOkTest Class Doc Comment
 *
 * @category    Class
 * @description 200 ok object
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetWarsWarIdOkTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetWarsWarIdOk"
     */
    public function testGetWarsWarIdOk()
    {
    }

    /**
     * Test attribute "aggressor"
     */
    public function testPropertyAggressor()
    {
    }

    /**
     * Test attribute "allies"
     */
    public function testPropertyAllies()
    {
    }

    /**
     * Test attribute "declared"
     */
    public function testPropertyDeclared()
    {
    }

    /**
     * Test attribute "defender"
     */
    public function testPropertyDefender()
    {
    }

    /**
     * Test attribute "finished"
     */
    public function testPropertyFinished()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "mutual"
     */
    public function testPropertyMutual()
    {
    }

    /**
     * Test attribute "open_for_allies"
     */
    public function testPropertyOpenForAllies()
    {
    }

    /**
     * Test attribute "retracted"
     */
    public function testPropertyRetracted()
    {
    }

    /**
     * Test attribute "started"
     */
    public function testPropertyStarted()
    {
    }
}
