<?php
/**
 * CalendarApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CalendarApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CalendarApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getCharactersCharacterIdCalendar
     *
     * List calendar event summaries.
     *
     */
    public function testGetCharactersCharacterIdCalendar()
    {
    }

    /**
     * Test case for getCharactersCharacterIdCalendarEventId
     *
     * Get an event.
     *
     */
    public function testGetCharactersCharacterIdCalendarEventId()
    {
    }

    /**
     * Test case for getCharactersCharacterIdCalendarEventIdAttendees
     *
     * Get attendees.
     *
     */
    public function testGetCharactersCharacterIdCalendarEventIdAttendees()
    {
    }

    /**
     * Test case for putCharactersCharacterIdCalendarEventId
     *
     * Respond to an event.
     *
     */
    public function testPutCharactersCharacterIdCalendarEventId()
    {
    }
}
