<?php
/**
 * CharacterApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CharacterApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CharacterApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getCharactersCharacterId
     *
     * Get character's public information.
     *
     */
    public function testGetCharactersCharacterId()
    {
    }

    /**
     * Test case for getCharactersCharacterIdAgentsResearch
     *
     * Get agents research.
     *
     */
    public function testGetCharactersCharacterIdAgentsResearch()
    {
    }

    /**
     * Test case for getCharactersCharacterIdBlueprints
     *
     * Get blueprints.
     *
     */
    public function testGetCharactersCharacterIdBlueprints()
    {
    }

    /**
     * Test case for getCharactersCharacterIdCorporationhistory
     *
     * Get corporation history.
     *
     */
    public function testGetCharactersCharacterIdCorporationhistory()
    {
    }

    /**
     * Test case for getCharactersCharacterIdFatigue
     *
     * Get jump fatigue.
     *
     */
    public function testGetCharactersCharacterIdFatigue()
    {
    }

    /**
     * Test case for getCharactersCharacterIdMedals
     *
     * Get medals.
     *
     */
    public function testGetCharactersCharacterIdMedals()
    {
    }

    /**
     * Test case for getCharactersCharacterIdNotifications
     *
     * Get character notifications.
     *
     */
    public function testGetCharactersCharacterIdNotifications()
    {
    }

    /**
     * Test case for getCharactersCharacterIdNotificationsContacts
     *
     * Get new contact notifications.
     *
     */
    public function testGetCharactersCharacterIdNotificationsContacts()
    {
    }

    /**
     * Test case for getCharactersCharacterIdPortrait
     *
     * Get character portraits.
     *
     */
    public function testGetCharactersCharacterIdPortrait()
    {
    }

    /**
     * Test case for getCharactersCharacterIdRoles
     *
     * Get character corporation roles.
     *
     */
    public function testGetCharactersCharacterIdRoles()
    {
    }

    /**
     * Test case for getCharactersCharacterIdStandings
     *
     * Get standings.
     *
     */
    public function testGetCharactersCharacterIdStandings()
    {
    }

    /**
     * Test case for getCharactersCharacterIdTitles
     *
     * Get character corporation titles.
     *
     */
    public function testGetCharactersCharacterIdTitles()
    {
    }

    /**
     * Test case for postCharactersAffiliation
     *
     * Character affiliation.
     *
     */
    public function testPostCharactersAffiliation()
    {
    }

    /**
     * Test case for postCharactersCharacterIdCspa
     *
     * Calculate a CSPA charge cost.
     *
     */
    public function testPostCharactersCharacterIdCspa()
    {
    }
}
