<?php
/**
 * ContractsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.19
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ContractsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContractsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getCharactersCharacterIdContracts
     *
     * Get contracts.
     *
     */
    public function testGetCharactersCharacterIdContracts()
    {
    }

    /**
     * Test case for getCharactersCharacterIdContractsContractIdBids
     *
     * Get contract bids.
     *
     */
    public function testGetCharactersCharacterIdContractsContractIdBids()
    {
    }

    /**
     * Test case for getCharactersCharacterIdContractsContractIdItems
     *
     * Get contract items.
     *
     */
    public function testGetCharactersCharacterIdContractsContractIdItems()
    {
    }

    /**
     * Test case for getContractsPublicBidsContractId
     *
     * Get public contract bids.
     *
     */
    public function testGetContractsPublicBidsContractId()
    {
    }

    /**
     * Test case for getContractsPublicItemsContractId
     *
     * Get public contract items.
     *
     */
    public function testGetContractsPublicItemsContractId()
    {
    }

    /**
     * Test case for getContractsPublicRegionId
     *
     * Get public contracts.
     *
     */
    public function testGetContractsPublicRegionId()
    {
    }

    /**
     * Test case for getCorporationsCorporationIdContracts
     *
     * Get corporation contracts.
     *
     */
    public function testGetCorporationsCorporationIdContracts()
    {
    }

    /**
     * Test case for getCorporationsCorporationIdContractsContractIdBids
     *
     * Get corporation contract bids.
     *
     */
    public function testGetCorporationsCorporationIdContractsContractIdBids()
    {
    }

    /**
     * Test case for getCorporationsCorporationIdContractsContractIdItems
     *
     * Get corporation contract items.
     *
     */
    public function testGetCorporationsCorporationIdContractsContractIdItems()
    {
    }
}
