<?php
/**
 * FleetsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.19
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FleetsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FleetsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteFleetsFleetIdMembersMemberId
     *
     * Kick fleet member.
     *
     */
    public function testDeleteFleetsFleetIdMembersMemberId()
    {
    }

    /**
     * Test case for deleteFleetsFleetIdSquadsSquadId
     *
     * Delete fleet squad.
     *
     */
    public function testDeleteFleetsFleetIdSquadsSquadId()
    {
    }

    /**
     * Test case for deleteFleetsFleetIdWingsWingId
     *
     * Delete fleet wing.
     *
     */
    public function testDeleteFleetsFleetIdWingsWingId()
    {
    }

    /**
     * Test case for getCharactersCharacterIdFleet
     *
     * Get character fleet info.
     *
     */
    public function testGetCharactersCharacterIdFleet()
    {
    }

    /**
     * Test case for getFleetsFleetId
     *
     * Get fleet information.
     *
     */
    public function testGetFleetsFleetId()
    {
    }

    /**
     * Test case for getFleetsFleetIdMembers
     *
     * Get fleet members.
     *
     */
    public function testGetFleetsFleetIdMembers()
    {
    }

    /**
     * Test case for getFleetsFleetIdWings
     *
     * Get fleet wings.
     *
     */
    public function testGetFleetsFleetIdWings()
    {
    }

    /**
     * Test case for postFleetsFleetIdMembers
     *
     * Create fleet invitation.
     *
     */
    public function testPostFleetsFleetIdMembers()
    {
    }

    /**
     * Test case for postFleetsFleetIdWings
     *
     * Create fleet wing.
     *
     */
    public function testPostFleetsFleetIdWings()
    {
    }

    /**
     * Test case for postFleetsFleetIdWingsWingIdSquads
     *
     * Create fleet squad.
     *
     */
    public function testPostFleetsFleetIdWingsWingIdSquads()
    {
    }

    /**
     * Test case for putFleetsFleetId
     *
     * Update fleet.
     *
     */
    public function testPutFleetsFleetId()
    {
    }

    /**
     * Test case for putFleetsFleetIdMembersMemberId
     *
     * Move fleet member.
     *
     */
    public function testPutFleetsFleetIdMembersMemberId()
    {
    }

    /**
     * Test case for putFleetsFleetIdSquadsSquadId
     *
     * Rename fleet squad.
     *
     */
    public function testPutFleetsFleetIdSquadsSquadId()
    {
    }

    /**
     * Test case for putFleetsFleetIdWingsWingId
     *
     * Rename fleet wing.
     *
     */
    public function testPutFleetsFleetIdWingsWingId()
    {
    }
}
