<?php
/**
 * OpportunitiesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.19
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OpportunitiesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OpportunitiesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getCharactersCharacterIdOpportunities
     *
     * Get a character's completed tasks.
     *
     */
    public function testGetCharactersCharacterIdOpportunities()
    {
    }

    /**
     * Test case for getOpportunitiesGroups
     *
     * Get opportunities groups.
     *
     */
    public function testGetOpportunitiesGroups()
    {
    }

    /**
     * Test case for getOpportunitiesGroupsGroupId
     *
     * Get opportunities group.
     *
     */
    public function testGetOpportunitiesGroupsGroupId()
    {
    }

    /**
     * Test case for getOpportunitiesTasks
     *
     * Get opportunities tasks.
     *
     */
    public function testGetOpportunitiesTasks()
    {
    }

    /**
     * Test case for getOpportunitiesTasksTaskId
     *
     * Get opportunities task.
     *
     */
    public function testGetOpportunitiesTasksTaskId()
    {
    }
}
