<?php
/**
 * PlanetaryInteractionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.19
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PlanetaryInteractionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PlanetaryInteractionApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getCharactersCharacterIdPlanets
     *
     * Get colonies.
     *
     */
    public function testGetCharactersCharacterIdPlanets()
    {
    }

    /**
     * Test case for getCharactersCharacterIdPlanetsPlanetId
     *
     * Get colony layout.
     *
     */
    public function testGetCharactersCharacterIdPlanetsPlanetId()
    {
    }

    /**
     * Test case for getCorporationsCorporationIdCustomsOffices
     *
     * List corporation customs offices.
     *
     */
    public function testGetCorporationsCorporationIdCustomsOffices()
    {
    }

    /**
     * Test case for getUniverseSchematicsSchematicId
     *
     * Get schematic information.
     *
     */
    public function testGetUniverseSchematicsSchematicId()
    {
    }
}
